-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 15:33:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tulane
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tulane` ;

-- -----------------------------------------------------
-- Schema tulane
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tulane` DEFAULT CHARACTER SET latin1 ;
USE `tulane` ;

-- -----------------------------------------------------
-- Table `tulane`.`t_user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tulane`.`t_user_info` ;

CREATE TABLE IF NOT EXISTS `tulane`.`t_user_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NULL COMMENT '昵称',
  `realname` VARCHAR(45) NULL COMMENT '真实姓名',
  `mobile` VARCHAR(45) NULL COMMENT '手机',
  `create_time` BIGINT(20) NULL,
  `update_time` BIGINT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `tulane`.`t_product_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tulane`.`t_product_info` ;

CREATE TABLE IF NOT EXISTS `tulane`.`t_product_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `number` INT NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '商品表';


-- -----------------------------------------------------
-- Table `tulane`.`t_order_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tulane`.`t_order_info` ;

CREATE TABLE IF NOT EXISTS `tulane`.`t_order_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(45) NOT NULL COMMENT '订单流水号',
  `user_id` INT NOT NULL COMMENT '用户ID',
  `total_price` DECIMAL(10,2) NULL COMMENT '总金额',
  `order_status` TINYINT(1) NULL COMMENT '订单状态 -1:已关闭 0:未支付 1.已支付 2.已完成',
  `create_time` BIGINT(20) NULL,
  `update_time` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `order_number_UNIQUE` (`order_number` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '订单表';


-- -----------------------------------------------------
-- Table `tulane`.`t_order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tulane`.`t_order_product` ;

CREATE TABLE IF NOT EXISTS `tulane`.`t_order_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(45) NOT NULL,
  `product_id` INT NULL COMMENT '产品ID',
  `product_number` INT NULL COMMENT '产品数量',
  `product_name` VARCHAR(45) NULL COMMENT '产品名称',
  `product_price` DECIMAL(10,2) NULL COMMENT '产品价格',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '订单产品表';


-- -----------------------------------------------------
-- Table `tulane`.`t_order_back_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tulane`.`t_order_back_info` ;

CREATE TABLE IF NOT EXISTS `tulane`.`t_order_back_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(45) NOT NULL COMMENT '订单流水号',
  `back_number` VARCHAR(45) NOT NULL COMMENT '退货流水号',
  `total_price` DECIMAL(10,2) NULL COMMENT '总金额',
  `create_time` BIGINT(20) NULL,
  `update_time` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `back_number_UNIQUE` (`back_number` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '订单退货单';


-- -----------------------------------------------------
-- Table `tulane`.`t_account_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tulane`.`t_account_info` ;

CREATE TABLE IF NOT EXISTS `tulane`.`t_account_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL COMMENT '用户ID',
  `money` DECIMAL(10,2) NULL COMMENT '余额',
  `create_time` BIGINT(20) NULL,
  `update_time` BIGINT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '账户表';


-- -----------------------------------------------------
-- Table `tulane`.`t_transfer_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tulane`.`t_transfer_info` ;

CREATE TABLE IF NOT EXISTS `tulane`.`t_transfer_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transfer_number` VARCHAR(45) NULL COMMENT '交易流水号',
  `relate_number` VARCHAR(45) NOT NULL COMMENT '关联流水 当transfer_type 为1, 表示订单流水, transfer_type 为2, 表示退货流水',
  `transfer_type` TINYINT(1) NULL COMMENT '交易类型 1: 流入 2:流出',
  `account_out` INT NOT NULL COMMENT '出钱账户',
  `account_in` INT NOT NULL COMMENT '入钱账户',
  `transfer_way` TINYINT(1) NULL COMMENT '交易方式: 1. 支付宝 2. 微信 3. 余额',
  `transfer_money` DECIMAL(10,2) NULL COMMENT '交易金额',
  `transfer_status` TINYINT(1) NULL COMMENT '交易状态: -1. 失败 0. 未支付 1. 支付完毕(未到账) 2.完成 ',
  `create_time` BIGINT(20) NULL,
  `update_time` BIGINT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '交易流水';


-- -----------------------------------------------------
-- Table `tulane`.`t_order_back_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tulane`.`t_order_back_product` ;

CREATE TABLE IF NOT EXISTS `tulane`.`t_order_back_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(45) NOT NULL COMMENT '冗余',
  `back_number` VARCHAR(45) NOT NULL COMMENT '退货流水号',
  `product_id` INT NOT NULL COMMENT '产品ID',
  `product_name` VARCHAR(45) NULL COMMENT '产品名称 ',
  `product_number` INT NULL COMMENT '产品数量 ',
  `product_price` DECIMAL(10,2) NULL COMMENT '产品价格',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '退货单产品表';


-- -----------------------------------------------------
-- Table `tulane`.`t_account_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tulane`.`t_account_record` ;

CREATE TABLE IF NOT EXISTS `tulane`.`t_account_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NULL COMMENT '账户ID',
  `transfer_number` VARCHAR(45) NULL,
  `transfer_money` DECIMAL(10,2) NULL COMMENT '交易金额',
  `transfer_type` TINYINT(1) NULL COMMENT '交易类型 1: 流入 2:流出',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '账户流水';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
